# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Setup Node.js environment
    - uses: actions/setup-node@v2
      with:
        node-version: '14'
    - name: NPM Publish
      # You may pin to the exact commit or the version.
      # uses: JS-DevTools/npm-publish@0f451a94170d1699fd50710966d48fb26194d939
      uses: JS-DevTools/npm-publish@v1
      with: 
        cmd: npm install
    
    - name: Creating build
      run: npm build
        
    - name: installing surge
      run: npm install -g surge
     
    - name: Deploying on surge
      run: surge ./build https://ziadeveloperportfolio.surge.sh/ --token ${{secrets.SURGE_TOKEN}}
